### ISSUE TITLE
Question: SAMLContextProvider NullPointerException in MetadataDisplayFilter calls

### ISSUE THREAD

**Issue by egmar** [spring-projects/spring-security-saml-dsl#39]
HI, I was trying to set-up SAML support ( using guide in https://developer.okta.com/blog/2017/03/16/spring-boot-saml ) in my Spring Boot sample (IdP is IBM TFIM) and was struggling due to `SAMLContextProvider` being null when calling /saml/metadata endpoint. 
I managed to work around by setting `manager`, `keyManager` and `contextProvider` properties of `MetadataDisplayFilter` object passed to:
```
chains.add(new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/metadata/**"),
			new MetadataDisplayFilter()));
```
Is this a correct approach or I missed something in my app configuration?

**Comment by goeh** [comment]
I got bitten by this to. The /saml/metadata endpoint/filter gives NPE because contextProvider is null. The reason it is null is because MetadataDisplayFilter is created with **new** so autowiring is not happening for the filter.
https://github.com/spring-projects/spring-security-saml-dsl/blob/7a6731c93260f3b533dc93b7519bece8504fbef5/spring-security-saml-dsl/src/main/java/org/springframework/security/extensions/saml2/config/SAMLConfigurer.java#L263

Until this is fixed I will try your workaround and set the required attributes myself.

**Comment by goeh** [comment]
This is how I did the workaround. It's still not using autowiring but instead sets the required properties directly. I'm not sure how to fix this problem the "right way".
```java
public class SAMLConfigurer ... {

    private FilterChainProxy samlFilter(SAMLEntryPoint samlEntryPoint, SAMLContextProvider contextProvider) {
        ...
        chains.add(new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/metadata/**"), metadataDisplayFilter(contextProvider)));
        ...
    }

    private MetadataDisplayFilter metadataDisplayFilter(SAMLContextProvider contextProvider) {
        MetadataDisplayFilter metadataDisplayFilter = new MetadataDisplayFilter();
        metadataDisplayFilter.setContextProvider(contextProvider);
        metadataDisplayFilter.setKeyManager(serviceProvider.keyManager);
        metadataDisplayFilter.setManager(cachingMetadataManager);
        return metadataDisplayFilter;
    }
    ...
```
With this fix I'm able to configure my web app as a service provider in *WSO2 Identity Server* by just specifying the metadata url https://localhost:8443/saml/metadata. Nice!

**Comment by asegarra** [comment]
Hit by this too, contextProvider for MetadataDisplayFilter is not set, fix above works.

**Comment by jdsimmons** [comment]
I have run into this problem using Spring Boot with SAML. This page leads me to believe that the problem was fixed, but no version of the Spring Security SAML extension I've tried thus far does not have the problem. I still get the null pointer exception when accessing /saml/metadata and as a result logout processing will not work with Okta, which actually uses that URL.

The workaround described above looks like it depends on checking out the source code for SAML extension and modifying it myself, which I shouldn't have to do if it was fixed a year ago.

What version of SAML extension has the fix and how do I get it?
